name: Release and Publish

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    name: Release and Publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore: release')"

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # We need to fetch all history and tags for git-version-all to work correctly
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

      - name: Build package
        run: yarn build

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Bump version, Publish, and Push
        run: |
          yarn version --patch --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "Publishing new version: $VERSION"

          # Publish to npm first to ensure it succeeds before we push changes
          npm publish --access public

          # Now commit the version change
          git add package.json
          git commit -m "chore: release v$VERSION"

          # Tag the new version
          git tag "v$VERSION"

          # Push the commit and tag back to the repository
          git push --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
